version: '3.0'

services:
  database:
    image: postgres:16.1
    container_name: proglib-database
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    expose: 
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DATABASE_USER -d $DATABASE_NAME -h localhost -p 5432" ]
      interval: 2s
      timeout: 2s
      retries: 5

  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: proglib-server
    volumes:
      - ./app:/opt/app
    ports:
      - 8000:8000
    env_file:
      - .env
    entrypoint: bash ./script/entrypoint.sh server
    depends_on:
      database:
        condition: service_healthy
    restart: always
