version: '3.0'

services:
  database:
    image: postgres:16.1
    container_name: progbook-database
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    expose: 
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./app:/opt/app
    ports:
      - 8000:8000
    env_file:
      - .env
    entrypoint: bash ./script/entrypoint.sh server
    depends_on:
      database:
        condition: service_healthy
    restart: always
