version: '3.0'

services:
  database:
    image: mongo:6.0.13
    volumes:
      - ./mongodb:/data/db
    container_name: mongodb
    env_file:
      - .env
    ports: 
      - 27017:27017

  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: backend
    volumes:
      - ./app:/opt/app
    ports:
      - 8000:8000
    env_file:
      - .env
    entrypoint: bash ./script/entrypoint.sh server
    restart: always
